feat(): create datepicker component
AKASHAorg/akasha-world-framework pull request #1890
Opened 2023-03-24 08:27 UTC by themonster2015

## Description

* Create datepicker component.
## Issues that will be closed

## Testing

## Checklist

- [x] I have read the **README** document
- [x] I have read the **CONTRIBUTING** document
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed
- [x] My commit message follows [Conventional Commit Guideline](https://conventionalcommits.org/)

2023-03-30 07:20 UTC, quininez requested changes

2023-03-30 07:20 UTC, quininez commented on ui/design-system-core/src/components/DatePicker/DateSelector.tsx
> +        <div key={index}>
no need for key here, you have it on the wrapper div

2023-03-30 07:20 UTC, quininez commented on ui/design-system-core/src/components/DatePicker/DateSelector.tsx
> +          key={index}
no need for key

2023-03-30 09:04 UTC, themonster2015 commented on ui/design-system-core/src/components/DatePicker/DateSelector.tsx
> +        <div key={index}>
Right. silly me :)

2023-04-12 12:27 UTC, quininez approved these changes, later dismissed

2023-04-12 15:51 UTC, quininez approved these changes

2023-04-12 15:51 UTC, merged