Feat: trending widget button
AKASHAorg/akasha-world-framework pull request #2064
Opened 2023-09-26 21:43 UTC by josenriagu

## Description

- create and implements new trending widget button

## Checklist

- [x] I have read the **README** document
- [x] I have read the **CONTRIBUTING** document
- [x] I have added tests to cover my changes
- [x] All new and existing tests passed
- [x] My commit message follows [Conventional Commit Guideline](https://conventionalcommits.org/)

2023-09-29 11:02 UTC, didd requested changes
We can do this using the existing `DuplexButton` and I am not seeing the reason for creating `TrendingWidgetButton` component. We can slightly adjust the existing `DuplexButton` and that will do it.

2023-09-29 11:03 UTC, themonster2015 commented
I just checked the Branch preview URL and it seems like the subscribe button is not working, as for the follow button, it expands the widget area on hovering.

2023-10-04 13:19 UTC, josenriagu commented
> I just checked the Branch preview URL and it seems like the subscribe button is not working, as for the follow button, it expands the widget area on hovering.

I have fixed the issue with subscribe/unsubscribe. the tagSubscriptions was returning null, now it falls back to []

2023-10-05 05:31 UTC, didd approved these changes

2023-10-05 07:16 UTC, merged