design system core documentation
AKASHAorg/akasha-world-framework pull request #2311
Opened 2024-06-10 05:10 UTC by themonster2015

## Description

## Issues that will be closed

## Testing

## Checklist

- [ ] I have read the **README** document
- [ ] I have read the **CONTRIBUTING** document
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed
- [ ] My commit message follows [Conventional Commit Guideline](https://conventionalcommits.org/)

2024-06-13 08:34 UTC, didd commented on libs/design-system-core/README.md
> +A button component with rounded borders. Has 2 variants: `primary` for the call-to-action
Has three variants :) text as well

2024-06-14 12:26 UTC, josenriagu commented on libs/design-system-core/src/components/Accordion/index.tsx
> + * />
```suggestion
* <Accordion open={true} accordionId='someId' titleNode={title} contentNode={content} customStyle='w-[15%]' />
```

2024-06-14 12:38 UTC, josenriagu requested changes

2024-06-14 12:38 UTC, josenriagu commented on libs/design-system-core/src/components/AppAvatar/index.tsx
> + * />
```suggestion
 * <AppAvatar avatar={avatar} appType={IntegrationTypes.APP} profileId={profileId} />
```

2024-06-14 12:38 UTC, josenriagu commented on libs/design-system-core/src/components/AppAvatar/index.tsx
> + *  An AppAvatar provides a fast and easy way to create an avatar component.
```suggestion
 * An AppAvatar provides a fast and easy way to create an avatar component.
```

2024-06-14 12:38 UTC, josenriagu commented on libs/design-system-core/src/components/AppIcon/index.tsx
> + *  An AppIcon component provides a fast and easy way to include a custom app icon
```suggestion
 * An AppIcon component provides a fast and easy way to include a custom app icon
```

2024-06-18 11:52 UTC, quininez approved these changes

2024-06-18 12:20 UTC, josenriagu approved these changes

2024-06-18 13:25 UTC, merged